[General]
allow-lan = true
mode = rule
log-level = info
external-controller = 127.0.0.1:9090

[Proxy]
DIRECT,,
REJECT,,

[Proxy Group]
全部节点 = select,美国节点,狮城节点,日本节点,香港节点,DIRECT
美国节点 = select,DIRECT
狮城节点 = select,DIRECT
日本节点 = select,DIRECT
香港节点 = select,DIRECT

[Rule]
#国内域名直连
DOMAIN-SUFFIX,baidu.com,DIRECT
DOMAIN-SUFFIX,qq.com,DIRECT
DOMAIN-SUFFIX,aliyun.com,DIRECT
DOMAIN-SUFFIX,taobao.com,DIRECT
DOMAIN-SUFFIX,163.com,DIRECT
DOMAIN-SUFFIX,bilibili.com,DIRECT

#海外全部走【全部节点】
DOMAIN-SUFFIX,openai.com,全部节点
DOMAIN-SUFFIX,youtube.com,全部节点
DOMAIN-SUFFIX,netflix.com,全部节点
DOMAIN-SUFFIX,telegram.org,全部节点
DOMAIN-SUFFIX,google.com,全部节点
DOMAIN-SUFFIX,microsoft.com,全部节点
DOMAIN-SUFFIX,apple.com,全部节点

FINAL,全部节点